@AuthService.Api_HostAddress = https://localhost:44356


POST {{AuthService.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "Jean@example.com",
  "password": "MotDePasseSecurise123!",
  "firstName": "Jean",
  "lastName": "Dupont"
}
###